const DATA_LOADED = 'DATA_LOADED';
const TOGGLE_SCREEN = 'TOGGLE_SCREEN';
const TOGGLE_CONTACT = 'TOGGLE_CONTACT';
const SHUFFLE = 'SHUFFLE';


export {DATA_LOADED, TOGGLE_SCREEN, TOGGLE_CONTACT, SHUFFLE}
