const TOGGLE_SCREEN = 'TOGGLE_SCREEN';
const TOGGLE_CONTACT = 'TOGGLE_CONTACT';
const SHUFFLE = 'SHUFFLE';
const LOAD_DATA_BEGIN = 'LOAD_DATA_BEGIN';
const LOAD_DATA_SUCCESS = 'LOAD_DATA_SUCCESS'
const LOAD_DATA_ERROR = 'LOAD_DATA_ERROR'
const LOAD_KEYS_BEGIN = 'LOAD_KEYS_BEGIN';
const LOAD_KEYS_SUCCESS = 'LOAD_KEYS_SUCCESS'
const LOAD_KEYS_ERROR = 'LOAD_KEYS_ERROR'

export {LOAD_DATA_BEGIN, LOAD_DATA_SUCCESS, LOAD_DATA_ERROR, LOAD_KEYS_BEGIN, LOAD_KEYS_SUCCESS, LOAD_KEYS_ERROR, TOGGLE_SCREEN, TOGGLE_CONTACT, SHUFFLE}
